export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS"
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS"

export const SEND_MESSAGE = "SEND_MESSAGE"
export const DELETE_MESSAGE = "DELETE_MESSAGE"
export const SELECT_MESSAGE = "SELECT_MESSAGE"