export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS"
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS"

export const SEND_MESSAGE = "SEND_MESSAGE"
export const DELETE_MESSAGE = "DELETE_MESSAGE"
export const SELECT_MESSAGE = "SELECT_MESSAGE"
export const CLEAN_SELECTED_MESSAGES = "CLEAN_SELECTED_MESSAGES" 
export const SELECT_ROOM = "SELECT_ROOM"
export const SEARCH_MESSAGE = "SEARCH_MESSAGE"